In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ Librerías cargadas correctamente")

✅ Librerías cargadas correctamente

In [2]:
df = pd.read_csv('../data/raw/TMDB_all_movies.csv')
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")
df.head()

Filas: 124
Columnas: 16

,id,title,vote_average,vote_count,status,release_date,runtime,imdb_id,original_language,overview,genres,production_companies,director,imdb_rating,imdb_votes,poster_path
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = pd.read_csv('../data/raw/TMDB_all_movies.csv')
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")
df.head()

Filas: 1214189
Columnas: 16

,id,title,vote_average,vote_count,status,release_date,runtime,imdb_id,original_language,overview,genres,production_companies,director,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.106,371.0,Released,1988-10-21,73.0,tt0094675,fi,A Finnish man goes to the city to find a job a...,"Comedy, Drama, Romance, Crime",Villealfa Filmproductions,Aki Kaurismäki,7.4,9829.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.300,439.0,Released,1986-10-17,74.0,tt0092149,fi,"Nikander, a rubbish collector and would-be ent...","Comedy, Drama, Romance",Villealfa Filmproductions,Aki Kaurismäki,7.4,8693.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.905,2851.0,Released,1995-12-09,98.0,tt0113101,en,It's Ted the Bellhop's first night on the job....,Comedy,"Miramax, A Band Apart","Quentin Tarantino, Robert Rodriguez, Alexandre...",6.7,117058.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,370.0,Released,1993-10-15,109.0,tt0107286,en,"Four young friends, while taking a shortcut en...","Action, Crime, Thriller","Largo Entertainment, JVC, Universal Pictures",Stephen Hopkins,6.6,21122.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.200,30.0,Released,2006-01-01,80.0,tt0825671,en,Timo Novotny labels his new project an experim...,Documentary,inLoops,Timo Novotny,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg

In [4]:
print(df.columns.tolist())
df.head()

['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date', 'runtime', 'imdb_id', 'original_language', 'overview', 'genres', 'production_companies', 'director', 'imdb_rating', 'imdb_votes', 'poster_path']

,id,title,vote_average,vote_count,status,release_date,runtime,imdb_id,original_language,overview,genres,production_companies,director,imdb_rating,imdb_votes,poster_path
0,2,Ariel,7.106,371.0,Released,1988-10-21,73.0,tt0094675,fi,A Finnish man goes to the city to find a job a...,"Comedy, Drama, Romance, Crime",Villealfa Filmproductions,Aki Kaurismäki,7.4,9829.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg
1,3,Shadows in Paradise,7.300,439.0,Released,1986-10-17,74.0,tt0092149,fi,"Nikander, a rubbish collector and would-be ent...","Comedy, Drama, Romance",Villealfa Filmproductions,Aki Kaurismäki,7.4,8693.0,/nj01hspawPof0mJmlgfjuLyJuRN.jpg
2,5,Four Rooms,5.905,2851.0,Released,1995-12-09,98.0,tt0113101,en,It's Ted the Bellhop's first night on the job....,Comedy,"Miramax, A Band Apart","Quentin Tarantino, Robert Rodriguez, Alexandre...",6.7,117058.0,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg
3,6,Judgment Night,6.500,370.0,Released,1993-10-15,109.0,tt0107286,en,"Four young friends, while taking a shortcut en...","Action, Crime, Thriller","Largo Entertainment, JVC, Universal Pictures",Stephen Hopkins,6.6,21122.0,/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg
4,8,Life in Loops (A Megacities RMX),7.200,30.0,Released,2006-01-01,80.0,tt0825671,en,Timo Novotny labels his new project an experim...,Documentary,inLoops,Timo Novotny,8.1,285.0,/7ln81BRnPR2wqxuITZxEciCe1lc.jpg

In [5]:
faltantes = df.isnull().sum()
print(faltantes)

id                           0
title                       11
vote_average                 0
vote_count                   0
status                       0
release_date            128810
runtime                      0
imdb_id                 540477
original_language            0
overview                186475
genres                  326357
production_companies    628855
director                195544
imdb_rating             741539
imdb_votes              741539
poster_path             297054
dtype: int64